// <auto-generated />
namespace SimpleMoney.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init1));
        
        string IMigrationMetadata.Id
        {
            get { return "201211081411520_Init1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
